version: "3.1"
services:
  recruit_tracker_api:
    container_name: recruit_tracker_api
    build:
      context: "."
      dockerfile: "./Dockerfile"
    restart: always
    ports:
      - 5000:3000
    networks:
      - rt
networks:
  rt:
    external: true
